config/routes.rb
Rails.application.routes.draw do

  resource :user, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  root to: redirect("/user/new")

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord

  has_many :projects
  
  validates :name, presence: true

end

app/models/company_user.rb
class CompanyUser < ApplicationRecord
  belongs_to :company
  belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord

  belongs_to :company
  
  validates :name, presence: true

end

app/models/project_user.rb
class ProjectUser < ApplicationRecord
  belongs_to :project
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private

  def redirect_if_logged_in
    return unless logged_in?
    redirect_to user_path
  end

  def redirect_if_logged_out
    return if logged_in?
    redirect_to new_session_path
  end

  def logged_in?
    !session[:user_id].nil?
  end
  helper_method :logged_in?

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :redirect_if_logged_in,   only: [:new, :create]
  before_action :redirect_if_logged_out,  only: [:destroy]

  def new
  end

  def create
    @user = User.find_by(email: session_params[:email])

    if @user
      session[:user_id] = @user.id
      flash[:success] = "You are logged in"
      redirect_to user_path
    else
      flash[:error] = "Failed to log in, please try again"
      redirect_to action: :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You are now logged out"
    redirect_to new_session_path
  end

  private
  def session_params
    params.fetch(:session, {}).permit(:email)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_if_logged_in,   only: [:new, :create]
  before_action :redirect_if_logged_out,  only: [:show]

  def new
    @user = User.new(user_params)
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Thank you for signing up"
      redirect_to action: :show
    else
      flash[:error] = "Please complete all required info and try again"
      redirect_to action: :new
    end
  end

  def show
    @user = User.find(session[:user_id])
  end

private
  def user_params
    params.fetch(:user, {}).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_alert.html.haml
- alert_classes = { error: "danger", success: "success" }
- flash.each do |type, messages|
  - [messages].flatten.each do |message|
    %div{ class: "alert alert-#{alert_classes[type.to_sym] || type}" }
      .container
        = message

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Let Me In
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload"
    = javascript_include_tag "application", "data-turbolinks-track": "reload"
    = stylesheet_link_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"

  %body
    %nav.navbar.navbar-light.bg-light
      .container
        = link_to "Home", root_path, class: "navbar-brand"
        - if logged_in?
          .navbar-text
            = link_to "Logout", session_path, method: :delete

    = render partial: "layouts/alert"

    .container.pt-5.pb-5
      = yield

app/views/users/new.html.haml
%h1 Sign up

%p Please enter your name and email to sign up

.row
  .col
    = form_with model: @user, url: user_path do |f|
      .form-group
        = f.text_field :name, class: "form-control", placeholder: "Name"
      .form-group
        = f.text_field :email, class: "form-control", placeholder: "E-mail"
      = f.submit "Signup", class: "btn btn-primary"
      = link_to "or login", new_session_path, class: "btn btn-link"

  .col

app/views/users/show.html.haml
%p Welcome #{@user.name}!

%p This is your dashboard.